### DISCUSSION TITLE
Update BIDScoin from 3.7.0 to 4.2.0

### DISCUSSION THREAD

**Discussion by marcelzwiers** [neurodesk/neurodesk.github.io-hugo#371] [New Tool]
Hello all,

I noticed that the BIDScoin app in neurodesk is outdated and that a few of BIDScoin's entry points (bidsapps and other utilities) are missing / need updating. Also, the Ubuntu base image of your container doesn't need a backport to Qt5, you can simply pip install from pypi (and include the extras, e.g. `pip install bidscoin[all]`). I'm happy to assist if you have any questions.

Best,
Marcel (I'm the main BIDScoin developer)

**Comment by karl-koschutnig** [comment]
Hello,
An update would be very much appreciated! 

Best, Karl

**Reply by stebo85** [reply]
Dear @marcelzwiers , that would be wonderful :) could you directly propose the changes here through a pull request?

https://github.com/NeuroDesk/neurocontainers/recipes/bidscoin/build.sh

thank you so much 
Steffen

**Comment by marcelzwiers** [comment]
The relevant parts from the [pyproject.toml file](https://github.com/Donders-Institute/bidscoin/blob/master/pyproject.toml):

```toml
[project.optional-dependencies]
dcm2niix2bids    = ['dcm2niix']
spec2nii2bids    = ['spec2nii >= 0.6.1']
deface           = ['pydeface', 'drmaa']
pet2bids         = ['pypet2bids >= 1.0.12']
# phys2bidscoin    = ['bioread >= 1.0.5', 'pymatreader >= 0.0.24', 'duecredit', 'phys2bids >= 2.0.0, < 3.0.0']
all              = ['bidscoin[dcm2niix2bids,spec2nii2bids,deface,pet2bids]']    # + phys2bidscoin
dev              = ['bidscoin[spec2nii2bids,deface,pet2bids]', 'tox', 'pytest', 'sphinx-rtd-theme', 'myst-parser'] # + phys2bidscoin

[project.scripts]
bidscoin         = 'bidscoin.bcoin:main'
bidseditor       = 'bidscoin.bidseditor:main'
bidsmapper       = 'bidscoin.bidsmapper:main'
bidscoiner       = 'bidscoin.bidscoiner:main'
echocombine      = 'bidscoin.bidsapps.echocombine:main'
deface           = 'bidscoin.bidsapps.deface:main'
medeface         = 'bidscoin.bidsapps.medeface:main'
skullstrip       = 'bidscoin.bidsapps.skullstrip:main'
slicereport      = 'bidscoin.bidsapps.slicereport:main'
dicomsort        = 'bidscoin.utilities.dicomsort:main'
bidsparticipants = 'bidscoin.utilities.bidsparticipants:main'
rawmapper        = 'bidscoin.utilities.rawmapper:main'
physio2tsv       = 'bidscoin.utilities.physio2tsv:main'
plotphysio       = 'bidscoin.utilities.plotphysio:main'
```

And for the relevant part of the [container](https://github.com/Donders-Institute/bidscoin/blob/master/Dockerfile), this is what is needed for a `python:3.10-slim` base image:
```dockerfile
# First install pyqt5 as Debian package to solve dependencies issues occurring when installed with pip
# Then install the latest stable BIDScoin Qt5 release from Github (install the normal Qt6 branch from PyPi when using recent base images such as Ubuntu:22.04)
ENV PIP_NO_CACHE_DIR=off
RUN apt update && apt -y --no-install-recommends install pigz curl python3-pyqt5 python3-pyqt5.qtx11extras git && apt clean; \
    pip install --upgrade pip; \
    pip install bidscoin[spec2nii2bids,deface,pet2bids]@git+https://github.com/Donders-Institute/bidscoin@v4.2.0+qt5
```
So if you have an `Ubuntu:22.04` base image (as I think you do) then the Qt5 part can be skipped and simply be replaced with something like:
```dockerfile
ENV PIP_NO_CACHE_DIR=off
RUN apt update && apt -y --no-install-recommends install pigz curl && apt clean; \
    pip install --upgrade pip; \
    pip install bidscoin[spec2nii2bids,deface,dcm2niix]
```
